name: Build and Deploy

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+']

# Workflowsで使用する環境変数を定義
env:
  REPOSITORY_NAMESPACE: n-creativesystem
  REGISTRY_HOSTNAME: ghcr.io
  IMAGE_NAME: api-rback

  jobs:
    setup-build-publish:
      name: Setup, Build, Publish, and Deploy
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: version
          id: version
          run: |
            echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

        # Docker imageのビルド
        - name: Build with Docker
          run: |
            VERSION=${{ steps.version.outputs.VERSION }}
            docker build -f docker/embed.dockerfile -t ${REGISTRY_HOSTNAME}/${REPOSITORY_NAMESPACE}/${IMAGE_NAME}:${VERSION}-embed .
            docker tag ${REGISTRY_HOSTNAME}/${REPOSITORY_NAMESPACE}/${IMAGE_NAME}:${VERSION}-embed ${REGISTRY_HOSTNAME}/${REPOSITORY_NAMESPACE}/${IMAGE_NAME}:latest

        # ビルド済みのイメージをGithub PackagesへPush
        - name: Push the image to Github Packages
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          run: |
            VERSION=${{ steps.version.outputs.VERSION }}
            echo $GITHUB_TOKEN | docker login $REGISTRY_HOSTNAME -u $GITHUB_ACTOR --password-stdin
            docker push ${REGISTRY_HOSTNAME}/${REPOSITORY_NAMESPACE}/${IMAGE_NAME}:${VERSION}-embed
            docker push ${REGISTRY_HOSTNAME}/${REPOSITORY_NAMESPACE}/${IMAGE_NAME}:latest
